config/routes.rb
Rails.application.routes.draw do



  
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    collection do
      
      get :singup
      #get :singin
      get :main
    end
  end

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/servie.rb
class Servie < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password
    validates :name,:username,:password, presence: true
    validates :username, uniqueness: true
    #attr_accessor :password,:confimpassword
    #attr_accessor   :errors
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # before_action :ensure_login

    # protected
    # def ensure_login

    #     redirect_to singin_users_path unless session[:checkuser_id]
    #     #if session have nothing then it go on login page
    
    # end


  protect_from_forgery with: :exception   
  private   
  def current_user   
    User.where(id: session[:checkuser_id] ).first   
  end   
  helper_method :current_user   
end

app/controllers/servies_controller.rb
class ServiesController < ApplicationController

    

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create #find

    @user = User.new( params.require(:users).permit(:username,:password_digest))
    
    if User.exists?(:username => @user.username)
        @checkuser = User.where("username=?", @user.username)
        #@user = User.new(user_params_singin)
        if @checkuser[0].password == @user.password
            session[:checkuser_id] = @checkuser[0].id
            flash[:notice]="Successfully loged in!!!!!"
            redirect_to main_users_path
        else
            flash[:notice]="Enter correct password"
            render 'new'
        end
    else 
        flash[:notice]="Enter correct username"
        render 'new'
    end
  end

  def destroy
    session[:checkuser_id] = nil   
    #reset_session #wipe out session and everything in it
    redirect_to users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    #skip_before_action :ensure_login, only: [:singin] 

    def singup #registration
        @user = User.new
    end

    def create 
        @user = User.new(user_params)  
        if @user.save
            session[:checkuser_id] = @user.id   
            redirect_to  sessions_new_path
        else 
            render 'singup'
        end
    end


    def singin   #login
        if params[:users]
            #in session
        end
    end


   
    def index
        
    end

    def destroy
       

    end

    private 
    def user_params
        params.require(:users).permit(:name,:username,:password,:password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/servies_helper.rb
module ServiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/servies/serviceprovider_details.html.erb
<h1> Add details of service </h1>

<%= form_with scope: :user,url: users_path , local: true do |f| %>
    
        <%= f.text_field :image, placeholder: "Image" %> <br><br>
        <%= f.text_field :service_name, placeholder: ":service_name" %> <br><br>
        <%= f.text_field :address, placeholder: "address" %> <br><br>
        <%= f.text_field :city, placeholder: "city" %> <br><br>
        <%= f.text_field :contacty, placeholder: "contact" %> <br><br>
        <%= f.text_field :description, placeholder: "description" %> <br><br>
        <%= f.submit "submit", :name=>"submit" %>
<% end %>

app/views/users/index.html.erb
<% if current_user %>  
Logged in as <%= current_user.username %>.  
<%= link_to "Log Out", sessions_destroy_path %>  
<% else %>  
<%= link_to "Sign Up", singup_users_path %> or  
<%= link_to "Log In", sessions_new_path %>  
<% end %>  

app/views/users/main.html.erb
<h1> main page of web application </h1>

<h4> banquet hall </h4>
<%= link_to "banquet hall", users_path%>
<h4> party plots </h4>
<h4> music </h4>
<h4> decoretion </h4>
<h4> cetrine </h4>

app/views/users/singin.html.erb
<h1> login </h1>


<%= form_with scope: :users ,url:  singin_users_path,method: :get , local: true  do |f| %>
    <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
    <%= f.text_field :username, placeholder: "UserName" %> <br><br>
    <%= f.text_field :password, placeholder: "Password" %> <br><br>
    <%= f.submit "login" , :name=>"login" %>
<% end %>




<%= link_to "register", singup_users_path %>

app/views/users/singup.html.erb
<h1> register </h1>

<%= form_with scope: :users ,url: users_path , local: true do |f| %>
    <% if @user.errors.try(:any?) %>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
    <% end %>
        <%= f.text_field :name, placeholder: "Name" %> <br><br>
        <%= f.text_field :username, placeholder: "UserName" %> <br><br>
        <%= f.password_field :password, placeholder: "Password" %> <br><br>
        <%= f.password_field :password_confirmation, placeholder: "password_confirmation" %> <br><br>
        <%= f.submit "singup", :name=>"singup" %>
<% end %>